FROM python:3.11-slim
LABEL maintainer="Assignment #4"
LABEL description="Custom Superhero API Exporter"

WORKDIR /app
COPY requirements-prometheus.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["python", "custom_exporter.py"]
